apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  # Ensure only one replica, as MongoDB typically runs as a single primary instance in this setup
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        role: mongodb
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
          # Load credentials and database name from the Secret
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_DATABASE
        resources:
          requests:
            cpu: "400m"
            memory: "800Mi"
          limits:
            cpu: "1500m"
            memory: "2Gi"
        # Mount the PVC to the MongoDB data directory
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # This will be the DNS name for Spark workers to connect to
  labels:
    app: mongodb
spec:
  # ClusterIP exposes the service only within the cluster
  type: ClusterIP 
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb