apiVersion: v1
kind: Service
metadata:
  name: kafka-headless # Used by the StatefulSet for stable networking (kafka-0.kafka-headless)
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: k8s-internal
  - port: 9093
    name: controller
  clusterIP: None # Makes the service 'headless'
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service # Client access Service (e.g., Spark will connect to 'kafka-service:9092')
  labels:
    app: kafka
spec:
  type: ClusterIP 
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: "kafka-headless" # Must match the headless service name
  replicas: 1 # Single broker/controller node
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        role: kafka-broker
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 9092 # Internal Listener Port
        - containerPort: 9093 # Controller Port
        
        # Load all configuration from the ConfigMap
        envFrom:
          - configMapRef:
              name: kafka-config
        
        # Dynamically inject the pod name to construct the advertised listener FQDN
        env:
          - name: KAFKA_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        
        # Health check using a simple Kafka command
        livenessProbe:
          exec:
            command: ["kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        
      volumes:
      # Use the PVC defined in kafka-pvc.yaml
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-pvc