apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: hdfs
  labels:
    app: hdfs-namenode
spec:
  ports:
  - port: 9000
    name: fs
  - port: 9870
    name: web
  clusterIP: None
  selector:
    app: hdfs-namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  serviceName: hdfs-namenode
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      nodeSelector:
        role: infra-master
      containers:
      - name: hdfs-namenode
        image: apache/hadoop:3.4.1
        resources:
          requests:
            cpu: "1000m"  # Request 1 full core (1000 millicores)
            memory: "2Gi" # Request 2 Gigabytes of memory
          limits:
            cpu: "2000m"  # Limit to 2 full cores
            memory: "3Gi" # Limit to 3 Gigabytes of memory
        command:
          - "/bin/bash"
          - "-c"
          - |
            mkdir -p /hadoop/dfs/name
            /opt/hadoop/bin/hdfs --config /etc/hadoop namenode
        ports:
        - containerPort: 9000
          name: fs
        - containerPort: 9870
          name: web
        volumeMounts:
        - name: hdfs-config-volume
          mountPath: /etc/hadoop
        - name: namenode-data # Mount the persistent data directory
          mountPath: /hadoop/dfs/name
        env:
        - name: HADOOP_MAPRED_HOME
          value: /opt/hadoop
        - name: HADOOP_CONF_DIR
          value: /etc/hadoop
      volumes:
      - name: hdfs-config-volume
        configMap:
          name: hdfs-config # You must ensure this ConfigMap exists
      - name: namenode-data
        persistentVolumeClaim:
          claimName: namenode-pvc-node0 # Ensures persistence on Infra Master node