apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hdfs-nodemanager
  namespace: hdfs
spec:
  selector:
    matchLabels:
      app: hdfs-nodemanager
  template:
    metadata:
      labels:
        app: hdfs-nodemanager
    spec:
      nodeSelector:
        role: hdfs-worker
      containers:
      - name: hdfs-nodemanager
        image: apache/hadoop:3.4.1
        command:
          - "/bin/bash"
          - "-c"
          - |
            # Clean up old data on startup
            rm -rf /tmp/hadoop-yarn/nm-local-dir/*
            rm -rf /var/log/hadoop/userlogs/*
            
            echo "Starting YARN NodeManager..."
            /opt/hadoop/bin/yarn --config /etc/hadoop nodemanager
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 8042
          name: web
        env:
        - name: JAVA_HOME
          value: "/usr/lib/jvm/jre"
        - name: HADOOP_CONF_DIR
          value: /etc/hadoop
        - name: SPARK_CONF_DIR
          value: /etc/spark
        volumeMounts:
        - name: hdfs-config-volume
          mountPath: /etc/hadoop
        - name: spark-config-volume
          mountPath: /etc/spark
        - name: nodemanager-local-dir
          mountPath: /tmp/hadoop-yarn/nm-local-dir
        - name: nodemanager-log-dir
          mountPath: /var/log/hadoop/userlogs
        readinessProbe:
          httpGet:
            path: /
            port: 8042
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8042
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: hdfs-config-volume
        configMap:
          name: hdfs-config
      - name: spark-config-volume
        configMap:
          name: spark-config
      - name: nodemanager-local-dir
        hostPath:
          path: /tmp/nodemanager-local
          type: DirectoryOrCreate
      - name: nodemanager-log-dir
        hostPath:
          path: /tmp/nodemanager-logs
          type: DirectoryOrCreate