apiVersion: v1
kind: Service
metadata:
  name: hdfs-resourcemanager
  namespace: hdfs
  labels:
    app: hdfs-resourcemanager
spec:
  ports:
  - port: 8032
    name: rpc
  - port: 8088
    name: web
  clusterIP: None
  selector:
    app: hdfs-resourcemanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-resourcemanager
  template:
    metadata:
      labels:
        app: hdfs-resourcemanager
    spec:
      nodeSelector:
        role: infra-master
      containers:
      - name: hdfs-resourcemanager
        image: apache/hadoop:3.4.1
        resources:
          requests:
            cpu: "500m"  # 0.5 core guaranteed
            memory: "1536Mi" # 1.5 GiB guaranteed
          limits:
            cpu: "1000m" # 1 core limit
            memory: "2Gi" # 2 GiB limit
        command:
          - "/bin/bash"
          - "-c"
          - |
            echo "export JAVA_HOME=/opt/java" >> /etc/hadoop/hadoop-env.sh
            /opt/hadoop/bin/yarn --config /etc/hadoop resourcemanager
        ports:
        - containerPort: 8032
          name: rpc
        - containerPort: 8088
          name: web
        env:
        - name: HADOOP_CONF_DIR
          value: /etc/hadoop
        volumeMounts:
        - name: hdfs-config-volume
          mountPath: /etc/hadoop
        readinessProbe:
          httpGet:
            path: /
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: hdfs-config-volume
        configMap:
          name: hdfs-config