apiVersion: v1
kind: Service
metadata:
  name: hdfs-resourcemanager
  namespace: hdfs
  labels:
    app: hdfs-resourcemanager
spec:
  type: ClusterIP  # Changed from None
  ports:
  - port: 8032
    name: rpc
    targetPort: 8032
  - port: 8031
    name: resource-tracker
    targetPort: 8031
  - port: 8030
    name: scheduler
    targetPort: 8030
  - port: 8088
    name: web
    targetPort: 8088
  - port: 8033
    name: admin
    targetPort: 8033
  selector:
    app: hdfs-resourcemanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-resourcemanager
  namespace: hdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-resourcemanager
  template:
    metadata:
      labels:
        app: hdfs-resourcemanager
    spec:
      nodeSelector:
        role: infra-master
      containers:
      - name: hdfs-resourcemanager
        image: apache/hadoop:3.4.1
        resources:
          requests:
            cpu: "500m"
            memory: "1536Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        command:
          - "/bin/bash"
          - "-c"
          - |
            echo "Starting YARN ResourceManager..."
            echo "Hostname: $(hostname)"
            /opt/hadoop/bin/yarn --config /etc/hadoop resourcemanager
        ports:
        - containerPort: 8032
          name: rpc
          protocol: TCP
        - containerPort: 8088
          name: web
          protocol: TCP
        - containerPort: 8030
          name: scheduler
          protocol: TCP
        - containerPort: 8031
          name: tracker
          protocol: TCP
        - containerPort: 8033
          name: admin
          protocol: TCP
        env:
        - name: JAVA_HOME
          value: "/usr/lib/jvm/jre"
        - name: HADOOP_CONF_DIR
          value: /etc/hadoop
        - name: YARN_RESOURCEMANAGER_HEAPSIZE
          value: "1536"
        volumeMounts:
        - name: hdfs-config-volume
          mountPath: /etc/hadoop
        readinessProbe:
          httpGet:
            path: /
            port: 8088
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8088
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      volumes:
      - name: hdfs-config-volume
        configMap:
          name: hdfs-config