# Producer settings to simulate velocity and keying/partitioning

bootstrap_servers: ${KAFKA_BROKERS:localhost:9092}
topic: ${KAFKA_TOPIC:hydraulic_sensor_data}
key_field: ${PRODUCER_KEY_FIELD:device_id}

data:
  csv_path: ${PRODUCER_CSV_PATH:./data/hydraulic_system.csv}
  event_time_column: event_time
  device_id_column: ${PRODUCER_DEVICE_ID_COLUMN:device_id}
  # Optional: map CSV headers to canonical schema fields
  column_mapping:
    device_id: device_id
    cycle_index: cycle_index
    event_time: event_time
    cooler_efficiency: cooler_efficiency_pct
    pressure1: pressure1_bar
    pressure2: pressure2_bar
    temperature_cooler_out: temperature_cooler_out_C

serialize:
  format: json
  schema_path: config/kafka/schema.json

rate_control:
  sleep_seconds: ${PRODUCER_SLEEP_SECONDS:0.005}
  batch_size: ${PRODUCER_BATCH_SIZE:500}

logging:
  level: INFO
