# Spark Batch Reports configuration

job:
  name: HydraulicReports
  schedule: "hourly,daily"

source:
  raw_path: ${SPARK_OUTPUT_RAW:hdfs://namenode:8020/data/hydraulic/raw}
  agg_path: ${SPARK_OUTPUT_AGG:hdfs://namenode:8020/data/hydraulic/aggregates}

reports:
  - name: last_24h_downtime
    lookback_hours: ${BATCH_REPORT_LOOKBACK_HOURS:24}
    logic:
      type: threshold_duration
      threshold_field: avg_cooler_efficiency
      below_threshold: ${ALERT_COOLER_EFFICIENCY_MIN_PCT:20}
  - name: weekly_temperature_trend
    lookback_days: ${WEEKLY_TREND_LOOKBACK_DAYS:7}
    logic:
      type: trend
      field: max_temperature

output:
  path: ${REPORTS_OUTPUT_PATH:hdfs://namenode:8020/reports/hydraulic}
  format: parquet
  mode: overwrite
