# MLlib training job configuration

job:
  name: HydraulicTraining

source:
  dataset_path: ${SPARK_OUTPUT_RAW:hdfs://namenode:8020/data/hydraulic/raw}

features:
  label_column: ${TRAIN_LABEL_COLUMN:cooler_condition}
  feature_columns: ${TRAIN_FEATURE_COLUMNS:cooler_efficiency_pct,pressure1_bar,pressure2_bar,temperature_cooler_out_C}
  test_split: ${TRAIN_TEST_SPLIT:0.2}

model:
  algorithm: ${TRAIN_ALGORITHM:decision_tree_classifier}
  params:
    maxDepth: 5
    maxBins: 32

output:
  model_path: ${TRAINING_OUTPUT_PATH:hdfs://namenode:8020/models/hydraulic}
  metrics_path: ${TRAINING_OUTPUT_PATH:hdfs://namenode:8020/models/hydraulic/metrics}
